<a href="https://colab.research.google.com/github/joaopedropastura/credit_score_ai/blob/main/v3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [69]:
!pip install -U scikit-learn
!pip install pandas
!pip install joblib


Looking in indexes: https://anu9rng:****@rb-artifactory.bosch.com/artifactory/api/pypi/python-virtual/simple
Looking in indexes: https://anu9rng:****@rb-artifactory.bosch.com/artifactory/api/pypi/python-virtual/simple
Looking in indexes: https://anu9rng:****@rb-artifactory.bosch.com/artifactory/api/pypi/python-virtual/simple


In [97]:
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from joblib import load, dump
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os
import re
from sklearn.preprocessing import LabelEncoder
from sklearn.decomposition import PCA
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.svm import SVC
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import NuSVC
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score
from sklearn.kernel_approximation import Nystroem
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score
from sklearn.linear_model import SGDRegressor
from sklearn.metrics import mean_squared_error
from sklearn.kernel_approximation import RBFSampler
from sklearn.model_selection import GridSearchCV


In [143]:
path = "./credit_score.csv"

source = pd.read_csv(path)
le = LabelEncoder()

C:\Users\disrct\AppData\Local\Temp\ipykernel_22156\1512321555.py:3: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  source = pd.read_csv(path)


In [144]:
sl = source['Credit_Score'].unique()


sl

array(['Good', 'Standard', 'Poor'], dtype=object)

In [145]:
source = source[source['Payment_Behaviour'] != '!@9#%8']

In [146]:
sla = source['Type_of_Loan'].unique()
#   ||

# source = source[source['Type_of_Loan'] != 'Not Specified' ]

source = source[(source['Type_of_Loan'] != 'Not Specified') & (source['Type_of_Loan'].notnull())]

# source = source[source['Type_of_Loan'].dropna()]

In [147]:
def convert_to_months(age):
    if type(age) == type('String'):
      age_split = age.split(' ')
      years = int(age_split[0])
      months = int(age_split[3])
      # Cálculo total em meses
      total_months = years * 12 + months
      return total_months


source['Credit_History_Age'] = source['Credit_History_Age'].apply(convert_to_months)


In [148]:
source = source.drop(['ID', 'Customer_ID', 'SSN', 'Name'], axis=1)

In [149]:
source = source.head(3000)


In [150]:
Month = source["Month"].unique()
Credit_History_Age = source['Credit_History_Age'].unique()
Occupation = source["Occupation"].unique()
Credit_Mix = source["Credit_Mix"].unique()
Credit_Score = source["Credit_Score"].unique()
Payment_Behaviour = source['Payment_Behaviour'].unique()
Payment_of_Min_Amount = source["Payment_of_Min_Amount"].unique()
Type_of_Loan = source["Type_of_Loan"].unique()

In [151]:
le.fit(Month)
source['Month'] = le.transform(source['Month'])

le.fit(Type_of_Loan)
source['Type_of_Loan'] = le.transform(source['Type_of_Loan'])

le.fit(Payment_of_Min_Amount)
source['Payment_of_Min_Amount'] = le.transform(source['Payment_of_Min_Amount'])

le.fit(Credit_History_Age)
source['Credit_History_Age'] = le.transform(source['Credit_History_Age'])

le.fit(Occupation)
source['Occupation'] = le.transform(source['Occupation'])

le.fit(Credit_Mix)
source['Credit_Mix'] = le.transform(source['Credit_Mix'])

le.fit(Credit_Score)
source['Credit_Score'] = le.transform(source['Credit_Score'])

le.fit(Payment_Behaviour)
source['Payment_Behaviour'] = le.transform(source['Payment_Behaviour'])

In [152]:
source["Annual_Income"] = source["Annual_Income"].str[:-1]

In [153]:
def filterAge(age):
  try:
    pattern = r'\b\d+(?:[-_]\d+)*\b\s+'
    number = re.findall(pattern, age)
    return ' '.join(number)
  except:
    return age


for elem in source:

  source[elem] = source[elem].apply(filterAge)



In [154]:
for elem in source:
  source[elem].replace('', 0, inplace=True)


In [83]:
# for column in source:
#   source[column] = source[column] /source[column].abs().max()



# source
# source = source.fillna(0)

In [155]:
source = source.dropna()

In [109]:
source

Month  Age  Occupation  Annual_Income  Monthly_Inhand_Salary  \
0          3    0          12              0            1824.843333   
6          4    0          12              0            1824.843333   
7          1    0          12              0            1824.843333   
8          3    0          15              0            3037.986667   
9          2    0          13              0            3037.986667   
...      ...  ...         ...            ...                    ...   
99991      1    0           1              0            1929.906667   
99994      6    0           9              0            3359.415833   
99995      0    0           9              0            3359.415833   
99996      7    0           9              0            3359.415833   
99997      5    0           9              0            3359.415833   

       Num_Bank_Accounts  Num_Credit_Card  Interest_Rate  Num_of_Loan  \
0                      3                4              3            0   
6                      3                4              3            0   
7                      3                4              3            0   
8                      2                4              6            0   
9                      2                4              6            0   
...                  ...              ...            ...          ...   
99991                 10                8             29            0   
99994                  4                6              7            0   
99995                  4                6              7            0   
99996                  4                6              7            0   
99997                  4                6           5729            0   

       Type_of_Loan  ...  Credit_Mix  Outstanding_Debt  \
0               128  ...           3                 0   
6               128  ...           1                 0   
7               128  ...           1                 0   
8               684  ...           1                 0   
9               684  ...           1                 0   
...             ...  ...         ...               ...   
99991          4912  ...           0                 0   
99994           683  ...           3                 0   
99995           683  ...           3                 0   
99996           683  ...           3                 0   
99997           683  ...           1                 0   

       Credit_Utilization_Ratio  Credit_History_Age  Payment_of_Min_Amount  \
0                     26.822620                 264                      1   
6                     22.537593                 270                      1   
7                     23.933795                 404                      1   
8                     24.464031                 318                      1   
9                     38.550848                 319                      1   
...                         ...                 ...                    ...   
99991                 37.140784                  74                      2   
99994                 39.323569                 376                      1   
99995                 34.663572                 377                      1   
99996                 40.565631                 378                      1   
99997                 41.255522                 379                      1   

       Total_EMI_per_month  Amount_invested_monthly  Payment_Behaviour  \
0                49.574949                      0.0                  2   
6                49.574949                      0.0                  5   
7                49.574949                      0.0                  1   
8                18.816215                      0.0                  5   
9                18.816215                      0.0                  0   
...                    ...                      ...                ...   
99991            60.964772                      0.0                  0   
99994            35.104023                      0.0

In [156]:
X = source.drop('Credit_Score', axis=1)
Y = source['Credit_Score']

X_train, X_test, Y_train, Y_test = \
  train_test_split(X, Y, test_size=0.2, random_state=50)

In [157]:
#RANDOM FOREST COM PCA

X = source.drop('Credit_Score', axis=1)
Y = source['Credit_Score']

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=500)

pca = PCA(n_components=23)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

model = DecisionTreeClassifier(max_depth=100, min_samples_split=36)

model.fit(X_train, Y_train)

Y_pred = model.predict(X_test)
Y_pred_train = model.predict(X_train)
accuracy = accuracy_score(Y_test, Y_pred)
accurac3y = accuracy_score(Y_train, Y_pred_train)

matrix = confusion_matrix(Y_test, Y_pred)

print(accuracy)
print(accurac3y)


0.6742596810933941
0.7940673131774102


In [167]:
#RANDOM FOREST COM PCA


X = source.drop('Credit_Score', axis=1)
Y = source['Credit_Score']

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=500)

pca = PCA(n_components=23)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

# 'class_weight': 'balanced_subsample', 'criterion': 'log_loss', 'max_features': 'log2'
# max_depth': 100, 'max_features': 'log2', 'min_samples_split': 10, 'n_estimators': 500
# 'max_depth': 200, 'max_features': 'log2', 'min_samples_split': 24, 'n_estimators': 100
model = RandomForestClassifier(max_depth=200, n_estimators = 100, min_samples_split=24, class_weight='balanced_subsample', criterion='log_loss', max_features='log2')

model.fit(X_train, Y_train)

Y_pred = model.predict(X_test)
Y_pred_train = model.predict(X_train)
accuracy = accuracy_score(Y_test, Y_pred)
accurac3y = accuracy_score(Y_train, Y_pred_train)


GridSearchCV(estimator=SVC(),
             param_grid={'max_depth': [1, 10], 'kernel': ('linear', 'rbf')})

matrix = confusion_matrix(Y_test, Y_pred)

print(accuracy)
print(accurac3y)


0.724373576309795
0.8459783228750714


In [120]:
dump(model, "randomForest.pkl")

['randomForest.pkl']

In [121]:
myModel = load("randomForest.pkl")


In [123]:
prediction = myModel.predict([[3.000000000, 0.000000000, 1.2000000001, 0.000000000,
       1.8248433303, 3.00000000, 4.000000000, 3.0000000000,
       0.0000000000, 1.1000000001, 3.0000000000, 0.000000000,
       0.0000000000, 4.0000000000, 3.0000000000, 0.000000000,
       2.682261961, 2.6200000002, 1.0000000000, 4.9574949201,
       0.0000000000, 2.0000000000, 0.0000000000]])



In [127]:
prediction = myModel.predict([[5.000000000, 0.000000000, 1.2000000001, 0.000000000,
       1.8248433303, 3.00000000, 4.000000000, 3.0000000000,
       0.0000000000, 1.1000000001, 3.0000000000, 0.000000000,
       0.0000000000, 4.0000000000, 3.0000000000, 0.000000000,
       2.682261961, 2.6200000002, 1.0000000000, 4.9574949201,
       0.0000000000, 2.0000000000, 0.0000000000]])

if(prediction == 0):
    print("Good")
elif(prediction == 1):
    print("Poor")
elif(prediction == 2):
    print("Standard")



Poor


In [132]:
def prediction(inputData):
    prediction = myModel.predict([inputData])
    temp = ''
    if(prediction == 0):
        temp = "Good"
    elif(prediction == 1):
        temp = "Poor"
    elif(prediction == 2):
        temp = "Standard"
    return temp

In [133]:
from flask import Flask, request

app = Flask(__name__)

@app.route('/prediction', methods=['POST'])
def predictionPost():
    data = request.json
    return prediction(data.get('data'))

app.run(port=8080)


 * Serving Flask app '__main__'
 * Debug mode: off


 * Running on http://127.0.0.1:8080


Press CTRL+C to quit
127.0.0.1 - - [17/Nov/2023 09:31:23] "POST /prediction HTTP/1.1" 200 -


In [129]:
def prediction(inputData):
    prediction = myModel.predict([inputData])

    if(prediction == 0):
        print("Good")
    elif(prediction == 1):
        print("Poor")
    elif(prediction == 2):
        print("Standard")
 


In [ ]:
sl = source.iloc[0].values

sl

array([3.00000000e+00, 0.00000000e+00, 1.20000000e+01, 0.00000000e+00,
       1.82484333e+03, 3.00000000e+00, 4.00000000e+00, 3.00000000e+00,
       0.00000000e+00, 1.10000000e+01, 3.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 4.00000000e+00, 3.00000000e+00, 0.00000000e+00,
       2.68226196e+01, 2.62000000e+02, 1.00000000e+00, 4.95749492e+01,
       0.00000000e+00, 2.00000000e+00, 0.00000000e+00, 0.00000000e+00])

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

X = source.drop('Credit_Score', axis=1)
Y = source['Credit_Score']

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=500)

pca = PCA(n_components=23)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

gb_model = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=500)

gb_model.fit(X_train, Y_train)

Y_pred_gb = gb_model.predict(X_test)

accuracy_gb = accuracy_score(Y_test, Y_pred_gb)
print("Precisão do Gradient Boosting Classifier no conjunto de teste:", accuracy_gb)

matrix_gb = confusion_matrix(Y_test, Y_pred_gb)
print("Matriz de Confusão do Gradient Boosting Classifier:\n", matrix_gb)


Precisão do Gradient Boosting Classifier no conjunto de teste: 0.6698932737652022
Matriz de Confusão do Gradient Boosting Classifier:
 [[1602   96  952]
 [ 273 3291 1407]
 [ 944 1648 5903]]


In [169]:
#melhores parametros para teste

from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

temp = source.head(1000)

X = temp.drop('Credit_Score', axis=1)
Y = temp['Credit_Score']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=500)

pca = PCA(n_components=23)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

model = RandomForestClassifier()

param_grid = {
    'n_estimators': [60, 80, 100],
    'max_depth': [100,150, 200],
    'criterion': [ 'log_loss'],
    'min_samples_split': [24, 26, 28],
    'max_features': ['log2'],
    'class_weight': ['balanced_subsample']
}

grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=5, scoring='accuracy')

grid_search.fit(X, Y)

best_params = grid_search.best_params_
print("Melhores parâmetros:", best_params)

best_model = grid_search.best_estimator_
Y_pred = best_model.predict(X_test)
accuracy = accuracy_score(Y_test, Y_pred)
print("Precisão no conjunto de teste com os melhores parâmetros:", accuracy)

matrix = confusion_matrix(Y_test, Y_pred)
print("Matriz de Confusão:\n", matrix)

# 'max_depth': 200, 'max_features': 'log2', 'min_samples_split': 24, 'n_estimators': 100
#  'max_depth': 200, 'max_features': 'log2', 'min_samples_split': 28, 'n_estimators': 100


Melhores parâmetros: {'class_weight': 'balanced_subsample', 'criterion': 'log_loss', 'max_depth': 100, 'max_features': 'log2', 'min_samples_split': 26, 'n_estimators': 80}
Precisão no conjunto de teste com os melhores parâmetros: 0.46
Matriz de Confusão:
 [[14  0 15]
 [12  0 50]
 [31  0 78]]


c:\Users\disrct\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [ ]:
#SVM COM PCA

X = source.drop('Credit_Score', axis=1)
Y = source['Credit_Score']

# Dividindo os dados em conjuntos de treino e teste
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=500)

# Aplicação do PCA apenas nos dados de treinamento
pca = PCA(n_components=23)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)


model = SVC()

model.fit(X_train, Y_train)

Y_pred = model.predict(X_test)
Y_pred_train = model.predict(X_train)
accuracy = accuracy_score(Y_test, Y_pred)
accurac3y = accuracy_score(Y_train, Y_pred_train)

matrix = confusion_matrix(Y_test, Y_pred)

print(accuracy)
print(accurac3y)


0.57
0.5208333333333334


In [ ]:
#NUSVC COM PCA

X = source.drop('Credit_Score', axis=1)
Y = source['Credit_Score']

# Dividindo os dados em conjuntos de treino e teste
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=500)

# Aplicação do PCA apenas nos dados de treinamento
pca = PCA(n_components=23)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)


model = make_pipeline(StandardScaler(), NuSVC())

model.fit(X_train, Y_train)

Y_pred = model.predict(X_test)
Y_pred_train = model.predict(X_train)
accuracy = accuracy_score(Y_test, Y_pred)
accurac3y = accuracy_score(Y_train, Y_pred_train)

matrix = confusion_matrix(Y_test, Y_pred)

print(accuracy)
print(accurac3y)


In [ ]:
#SGD

X = source.drop('Credit_Score', axis=1)
Y = source['Credit_Score']

# Dividindo os dados em conjuntos de treino e teste
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=500)

pca = PCA(n_components=23)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

model = SGDClassifier(loss="hinge", penalty="l2", max_iter=5)

model.fit(X_train, Y_train)

Y_pred = model.predict(X_test)
Y_pred_train = model.predict(X_train)
accuracy = accuracy_score(Y_test, Y_pred)
accurac3y = accuracy_score(Y_train, Y_pred_train)

matrix = confusion_matrix(Y_test, Y_pred)

print(accuracy)
print(accurac3y)

0.2916666666666667
0.3129166666666667


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_stochastic_gradient.py:713: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(


In [ ]:
#Kernel Approximation


X = source.drop('Credit_Score', axis=1)
Y = source['Credit_Score']

# Dividindo os dados em conjuntos de treino e teste
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=500)

pca = PCA(n_components=20)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

rbf_feature = RBFSampler(gamma=1, random_state=1)
X_features = rbf_feature.fit_transform(X_train)

model = SGDClassifier(max_iter=5)


model.fit(X_train, Y_train)

Y_pred = model.predict(X_test)
Y_pred_train = model.predict(X_train)
accuracy = model.score(Y_test, Y_pred)
accurac3y = model.score(Y_train, Y_pred_train)

matrix = confusion_matrix(Y_test, Y_pred)

print(accuracy)
print(accurac3y)